# Configuration
title:                SESA Slides 
tagline:              'powered by reveal.js'
url:                  https://sesa.github.io/slides 
baseurl:              'http://sesa.github.io/slides'
safe:                 true 
timezone:             America/New_York
encoding:             utf-8
markdown:             redcarpet
highlighter:          rouge
permalink:            pretty
exclude:              ['vendor']

collections:
  slides:
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ''
      type: 'slides'
    values:
      layout: 'slides'
